name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened        # Trigger when a PR is opened
      - synchronize   # Trigger when a PR is updated/changed
      - reopened      # Trigger when a previously closed PR is reopened

jobs:
  auto-merge:
    # Only merge dependabot's PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge Dependabot PRs
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout -qf FETCH_HEAD
          git merge origin/${{ github.base_ref }} --no-edit

      - name: Push the merge
        run: |
          git push origin HEAD:${{ github.head_ref }}