name: Python Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies only if requirements.txt is present
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Check Python syntax
      - name: Check for Syntax Errors
        run: |
          find . -name "*.py" -print0 | xargs -0 python -m py_compile
        
      # Run tests
      - name: Run Tests
        run: |
          pytest --disable-warnings